name: Release

on:
  push:
    branches:
      - main

jobs:
  docker-release-poller:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: poller/Dockerfile
          context: poller/
          push: true
          tags: |
            ghcr.io/huskehhh/revo-poller:latest

  docker-release-ui:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
        with:
          file: ui/Dockerfile
          context: ui/
          push: true
          tags: |
            ghcr.io/huskehhh/revo-ui:latest